import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import SideBar from "@/components/SideBar";
import { Box } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shopping List",
  description: "Generated by Arash",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body
        suppressHydrationWarning
        style={{ fontFamily: "var(--font-geist-sans), sans-serif" }}
      >
        <AppRouterCacheProvider>
          <Box
            sx={{
              display: "flex",
              minHeight: "100vh",
              flexDirection: { xs: "column", md: "row" },
              width: "100%",
            }}
          >
            <SideBar />
            <Box
              component="main"
              sx={{ flexGrow: 1, p: 4, backgroundColor: "#f8fafc" }}
            >
              {children}
            </Box>
          </Box>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
